site_name: "Marco's Notes"
site_url: https://notes.mpri.me
docs_dir: notes
site_description: "Marco's Notes"
site_author: "Marco Primi"
strict: false
theme:
  name: mkdocs
  custom_dir: custom_theme/

nav:
  - "â¤ï¸ Favorites":
    - "Art and Design": favorites/art.md
    - "Articles": favorites/articles.md
    - "Books": favorites/books.md
    - "Lectures and Talks": favorites/lectures.md
    - "Podcasts": favorites/podcasts.md
    - "Projects and initiatives": favorites/projects-and-initiatives.md
    - "Webcomics": favorites/webcomics.md
  - "ğŸ¦‹ Thoughts":
    - "ğŸ““ ãƒ» Diary": diary/index.md
    - "ğŸ“š ãƒ» Topics": topics/index.md
  - "ğŸ§­ Logs": logs/index.md
  - "ğŸ—ƒ Everything else": everything-else/index.md
