site_name: "Marco's Notes"
site_url: https://notes.mpri.me
docs_dir: notes
site_description: "Marco's Notes"
site_author: "Marco Primi"
strict: false
theme:
  name: mkdocs
  custom_dir: custom_theme/

nav:
  - "â¤ï¸ Favorites": favorites/index.md
  - "ğŸ¦‹ Thoughts":
    - "ğŸ““ ãƒ» Diary": diary/index.md
    - "ğŸ“š ãƒ» Topics": topics/index.md
  - "ğŸ§­ Logs": logs/index.md
  - "ğŸ—ƒ Everything else": everything-else/index.md
